export const accordionProvider: any = [
    {
        trigger: "How do i find my ideal location",
        content: "just give us your location and pefered biusness type",
    },
    {
        trigger: "can i change my prefrences  later",
        content: "Absolutely! flexibility is our middle name"
    },
    {
        trigger: "How quickly can i get results",
        content: "Faster than you can say `location location location`"
    }
]
export const locations = [
    "Agbado-Oke Odo",
    "Agboyi Ketu",
    "Apapa Iganmu",
    "Ayobo-Ipaja",
    "Badagry West",
    "Bariga",
    "Coker-Aguda",
    "Egbe-Idimu",
    "Ejigbo",
    "Eredo",
    "Eti-Osa East",
    "Iba",
    "Ifelodun",
    "Igando-Ikotun",
    "Igbogbo Baiyeku",
    "Ijede",
    "Ikorodu North",
    "Ikorodu West",
    "Ikosi Ejinrin",
    "Ikosi/Isheri",
    "Ikoyi/Obalende",
    "Imota",
    "Iru, Victoria Island",
    "Isolo",
    "Itire-Ikate",
    "Lagos Island East",
    "Lekki",
    "Mosan-Okunola",
    "Odi-Olowo",
    "Ojodu",
    "Ojokoro",
    "Olorunda",
    "Onigbongbo",
    "Oriade",
    "Orile Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Kosofe",
    "Mushin",
    "Oshodi-Isolo",
    "Ojo	",
    "Ikorodu",
    "Surulere",
    "Agege	",
    "Ifako-Ijaiye",
    "Somolu",
    "Amuwo-Odofin",
    "Lagos Mainland",
    "Ikeja",
    "Eti-Osa",
    "Badagry",
    "Apapa",
    "Lagos Island",
    "Epe",
    "Ibeju-Lekki",
];



